- name: Create a custom Docker network
  docker_network:
    name: logforge_network
    state: present

- name: Set up MongoDB container
  docker_container:
    name: mongo
    image: mongo:6.0
    state: started
    restart_policy: always
    ports:
      - "27017:27017"
    networks:
      - name: logforge_network
    volumes:
      - mongo_data:/data/db
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ lookup('env', 'MONGO_INITDB_ROOT_USERNAME') }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ lookup('env', 'MONGO_INITDB_ROOT_PASSWORD') }}"

- name: Run the FastAPI container
  docker_container:
    name: logforge-fastapi
    image: "{{ ecr_registry }}/logforge:latest"
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
    networks:
      - name: logforge_network
    env:
      MONGO_URL: "mongodb://mongo:27017"
      MONGO_INITDB_ROOT_USERNAME: "{{ lookup('env', 'MONGO_INITDB_ROOT_USERNAME') }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ lookup('env', 'MONGO_INITDB_ROOT_PASSWORD') }}"