services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: ./Dockerfile
    container_name: fastapi
    volumes:
      - ./fastapi:/app

    ports:
      - "8000:8000"
    network_mode: "host"
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     REACT_APP_API_URL: http://fastapi:8000
  #   depends_on:
  #     - fastapi

